GENERAL:
  task: train  # train, test
  manual_seed: 123
  dataset_dir: /home/gjt/SemanticPOSS/dataset/
  debug: False

DATA:
  dataset: SemanticPOSS
  classes_seg: 11
  classes_completion: 12

Segmentation:
  model_name: SubSparseConv
  m: 16 # 16 or 32
  block_residual: False
  seg_groups: 1
  block_reps: 1
  use_coords: False
  feature_dims: [16,32,48,64,80,96,112]

  input_channel: 3
  scale: 10   # voxel_size = 1 / scale, scale 10 (1cm)
  full_scale: [0, 2048]
  max_npoint: 250000
  mode: 4 # 4=mean

Completion:
  model_name: SSCNet
  m: 32
  feeding: feat # ['feat', 'prob', 'both']
  no_fuse_feat: False
  block_residual: True
  block_reps: 2
  use_coords: False
  mode: 0
  full_scale: [256, 256, 32]
  interaction: False
  pooling_type: mean
  fuse_k: 5
  point_cloud_range: [0, -25.6, -2, 51.2, 25.6, 4.4]
  voxel_size: 0.2
  search_k: 8
  feat_relation: False

TRAIN:
  epochs: 100
  train_workers: 8 # data loader workers
  optim: Adam # Adam or SGD
  batch_size: 4
  learning_rate: 0.001
  lr_decay: 0.7
  decay_step: 10
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 16  # also eval_freq
  uncertainty_loss: True
  loss_weight: [1.0, 0.8] # semantic_loss, completion_loss
  pretrain_path:
  train_from: 0
  seg_num_per_class: [2632722, 829245, 16063541, 1812243, 59342174, 1170307, 783713, 35259807, 2308931, 9040578, 3453465]
  complt_num_per_class: [26327220, 2632722, 829245, 16063541, 1812243, 59342174, 1170307, 783713, 35259807, 2308931, 9040578, 3453465]


